# Generated by Django 4.0.4 on 2022-06-03 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predmeti', '0002_rename_roles_predmeti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('upisan', 'Upisan'), ('polozen', 'Položen'), ('izgubljen_potpis', 'Izgubljen potpis')], default='upisan', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='predmeti',
            name='studenti',
            field=models.ManyToManyField(related_name='upisani_predmeti', through='predmeti.Upisi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='upisi',
            name='predmet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predmeti.predmeti'),
        ),
        migrations.AddField(
            model_name='upisi',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
