# Generated by Django 4.0.4 on 2022-06-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predmeti', '0003_upisi_predmeti_studenti_upisi_predmet_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predmeti',
            options={'verbose_name': 'Predmet', 'verbose_name_plural': 'Predmeti'},
        ),
    ]
