# Generated by Django 4.0.4 on 2022-06-03 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('korisnici', '0003_alter_roles_options'),
        ('predmeti', '0004_alter_predmeti_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmeti',
            name='studenti',
            field=models.ManyToManyField(blank=True, related_name='upisani_predmeti', through='predmeti.Upisi', to=settings.AUTH_USER_MODEL),
        ),
    ]
