# Generated by Django 4.0.4 on 2022-06-04 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predmeti', '0006_alter_predmeti_bodovi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmeti',
            name='bodovi',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Predmet ne može nositi manje od jednog boda.'), django.core.validators.MaxValueValidator(60, message='Predmet ne može iznositi više od 60 bodova.')]),
        ),
        migrations.AlterField(
            model_name='predmeti',
            name='sem_izvanredni',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Broj semestra mora biti između 1 i 16.'), django.core.validators.MaxValueValidator(16, message='Broj semestra mora biti između 1 i 16.')]),
        ),
        migrations.AlterField(
            model_name='predmeti',
            name='sem_redovni',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Broj semestra mora biti između 1 i 16.'), django.core.validators.MaxValueValidator(60, message='Broj semestra mora biti između 1 i 16.')]),
        ),
    ]
