# Generated by Django 4.0.4 on 2022-06-04 02:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predmeti', '0007_alter_predmeti_bodovi_alter_predmeti_sem_izvanredni_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upisi',
            options={'verbose_name': 'Upis', 'verbose_name_plural': 'Upisi'},
        ),
        migrations.AlterUniqueTogether(
            name='upisi',
            unique_together={('student_id', 'predmet_id')},
        ),
    ]
