# Generated by Django 4.0.4 on 2022-06-04 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predmeti', '0008_alter_upisi_options_alter_upisi_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmeti',
            name='nositelj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
