# Generated by Django 4.0.4 on 2022-06-23 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predmeti', '0009_alter_predmeti_nositelj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upisi',
            name='predmet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_pr', to='predmeti.predmeti'),
        ),
        migrations.AlterField(
            model_name='upisi',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_st', to=settings.AUTH_USER_MODEL),
        ),
    ]
