# Generated by Django 4.0.4 on 2022-06-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='korisnici',
            options={'verbose_name': 'Korisnik', 'verbose_name_plural': 'Korisnici'},
        ),
    ]
