# Generated by Django 4.0.4 on 2022-06-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0002_alter_korisnici_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
    ]
